export const translations = {
  en: {
    title: "AgriTrust",
    subtitle: "Blockchain Seed Verification",
    verify: "Verify Seed",
    register: "Register Seed",
    admin: "Admin Panel",
    scan_qr: "Scan QR Code",
    scan_instruction: "Position the QR code within the frame to verify authenticity.",
    genuine: "Genuine Seed",
    fake: "Fake / Unregistered",
    fraud: "Already Consumed",
    manufacturer: "Manufacturer",
    batch: "Batch Number",
    expiry: "Expiry Date",
    type: "Seed Type",
    ask_ai: "Ask Agri-Bot",
    ai_placeholder: "How do I plant this?",
    register_title: "Manufacturer Registration",
    register_btn: "Register Packet",
    fraud_map: "Fraud Heatmap",
    total_seeds: "Total Seeds",
    total_scans: "Total Scans",
    fraud_detected: "Fraud Detected",
    back: "Back",
    track: "Supply Chain",
    track_title: "Update Supply Chain",
    track_btn: "Update Location",
    journey: "Seed Journey",
    rewards: "Agri-Tokens",
    fraud_regions: "Regional Fraud Reports",
    login: "Login",
    username: "Username",
    password: "Password",
    login_btn: "Enter AgriTrust",
    logout: "Logout",
    welcome: "Welcome back",
    farmer: "Farmer",
    manufacturer_role: "Manufacturer",
    admin_role: "Administrator",
    distributor_role: "Distributor",
    retailer_role: "Retailer",
    inspector_role: "Quality Inspector",
    logistics_role: "Logistics Partner",
    profile: "Profile",
    profile_info: "Profile Information",
    stats: "Statistics",
    member_since: "Member Since",
    total_verifications: "Total Verifications",
    total_registrations: "Total Registrations",
    account_status: "Account Status",
    verified_account: "Verified",
    signup: "Sign Up",
    signin: "Sign In",
    create_account: "Create Account",
    have_account: "Already have an account?",
    no_account: "Don't have an account?",
    role_select: "Select Your Role",
    error_wrong_password: "Wrong Password! Please try again.",
    error_user_not_found: "User not found. Please sign up.",
    error_user_exists: "Username already exists.",
    signup_title: "Create Your Account",
    signup_subtitle: "Join AgriTrust to secure your seeds",
    signup_success: "Account created successfully! Please sign in.",
    confirm_password: "Confirm Password",
    error_password_mismatch: "Passwords do not match!",
    full_name: "Full Name",
    phone: "Phone Number",
    pref_lang: "Preferred Language",
    state: "State",
    district: "District",
    primary_crop: "Primary Crop",
    farm_area: "Farm Area (Acres)",
    company_name: "Company Name",
    license_no: "License Number",
    org_name: "Organization Name",
    access_level: "Access Level",
    edit_profile: "Edit Profile",
    save_profile: "Save Profile",
    profile_updated: "Profile updated successfully!",
    last_login: "Last Login",
    marathi: "Marathi",
    english: "English",
    hindi: "Hindi",
    intended_region: "Intended Region",
    lab_report: "Lab Report",
    report_fake: "Report Fake Seed",
    report_success: "Report submitted successfully!",
    points_earned: "Points Earned",
    expired: "Expired",
    recalled: "Recalled",
    near_expiry: "Near Expiry",
    recall_batch: "Recall Batch",
    download_qr: "Download QR",
    print_label: "Print Label",
    compliance_score: "Compliance Score",
    fraud_heatmap: "Fraud Heatmap",
    live_alerts: "Live Alerts",
    blockchain_audit: "Blockchain Audit",
  },
  hi: {
    title: "एग्रीट्रस्ट",
    subtitle: "ब्लॉकचेन बीज सत्यापन",
    verify: "बीज सत्यापित करें",
    register: "बीज पंजीकृत करें",
    admin: "एडमिन पैनल",
    scan_qr: "QR कोड स्कैन करें",
    scan_instruction: "सत्यता की जांच के लिए QR कोड को फ्रेम में रखें।",
    genuine: "असली बीज",
    fake: "नकली / अपंजीकृत",
    fraud: "पहले से उपयोग किया गया",
    manufacturer: "निर्माता",
    batch: "बैच नंबर",
    expiry: "समाप्ति तिथि",
    type: "बीज का प्रकार",
    ask_ai: "एग्री-बॉट से पूछें",
    ai_placeholder: "इसे कैसे रोपें?",
    register_title: "निर्माता पंजीकरण",
    register_btn: "पैकेट पंजीकृत करें",
    fraud_map: "धोखाधड़ी हीटमैप",
    total_seeds: "कुल बीज",
    total_scans: "कुल स्कैन",
    fraud_detected: "धोखाधड़ी पकड़ी गई",
    back: "पीछे",
    track: "आपूर्ति श्रृंखला",
    track_title: "आपूर्ति श्रृंखला अपडेट करें",
    track_btn: "स्थान अपडेट करें",
    journey: "बीज की यात्रा",
    rewards: "एग्री-टोकन",
    fraud_regions: "क्षेत्रीय धोखाधड़ी रिपोर्ट",
    login: "लॉगिन",
    username: "उपयोगकर्ता नाम",
    password: "पासवर्ड",
    login_btn: "एग्रीट्रस्ट में प्रवेश करें",
    logout: "लॉगआउट",
    welcome: "वापसी पर स्वागत है",
    farmer: "किसान",
    manufacturer_role: "निर्माता",
    admin_role: "प्रशासक",
    distributor_role: "वितरक",
    retailer_role: "खुदरा विक्रेता",
    inspector_role: "गुणवत्ता निरीक्षक",
    logistics_role: "रसद भागीदार",
    profile: "प्रोफ़ाइल",
    profile_info: "प्रोफ़ाइल जानकारी",
    stats: "आंकड़े",
    member_since: "सदस्यता की तारीख",
    total_verifications: "कुल सत्यापन",
    total_registrations: "कुल पंजीकरण",
    account_status: "खाते की स्थिति",
    verified_account: "सत्यापित",
    signup: "साइन अप करें",
    signin: "साइन इन करें",
    create_account: "खाता बनाएं",
    have_account: "क्या आपके पास पहले से खाता है?",
    no_account: "क्या आपके पास खाता नहीं है?",
    role_select: "अपनी भूमिका चुनें",
    error_wrong_password: "गलत पासवर्ड! कृपया पुनः प्रयास करें।",
    error_user_not_found: "उपयोगकर्ता नहीं मिला। कृपया साइन अप करें।",
    error_user_exists: "उपयोगकर्ता नाम पहले से मौजूद है।",
    signup_title: "अपना खाता बनाएं",
    signup_subtitle: "अपने बीजों को सुरक्षित करने के लिए एग्रीट्रस्ट से जुड़ें",
    signup_success: "खाता सफलतापूर्वक बनाया गया! कृपया साइन इन करें।",
    confirm_password: "पासवर्ड की पुष्टि करें",
    error_password_mismatch: "पासवर्ड मेल नहीं खाते!",
    full_name: "पूरा नाम",
    phone: "फ़ोन नंबर",
    pref_lang: "पसंदीदा भाषा",
    state: "राज्य",
    district: "जिला",
    primary_crop: "मुख्य फसल",
    farm_area: "खेत का क्षेत्रफल (एकड़)",
    company_name: "कंपनी का नाम",
    license_no: "लाइसेंस संख्या",
    org_name: "संगठन का नाम",
    access_level: "पहुंच स्तर",
    edit_profile: "प्रोफ़ाइल संपादित करें",
    save_profile: "प्रोफ़ाइल सहेजें",
    profile_updated: "प्रोफ़ाइल सफलतापूर्वक अपडेट की गई!",
    last_login: "पिछली बार लॉगिन",
    marathi: "मराठी",
    english: "अंग्रेजी",
    hindi: "हिंदी",
    intended_region: "लक्षित क्षेत्र",
    lab_report: "लैब रिपोर्ट",
    report_fake: "नकली बीज की रिपोर्ट करें",
    report_success: "रिपोर्ट सफलतापूर्वक सबमिट की गई!",
    points_earned: "अर्जित अंक",
    expired: "समाप्त",
    recalled: "वापस लिया गया",
    near_expiry: "समाप्ति के निकट",
    recall_batch: "बैच वापस लें",
    download_qr: "QR डाउनलोड करें",
    print_label: "लेबल प्रिंट करें",
    compliance_score: "अनुपालन स्कोर",
    fraud_heatmap: "धोखाधड़ी हीटमैप",
    live_alerts: "लाइव अलर्ट",
    blockchain_audit: "ब्लॉकचेन ऑडिट",
  },
  mr: {
    title: "एग्रीट्रस्ट",
    subtitle: "ब्लॉकचेन बियाणे पडताळणी",
    verify: "बियाणे पडताळणी",
    register: "बियाणे नोंदणी",
    admin: "प्रशासक पॅनेल",
    scan_qr: "QR कोड स्कॅन करा",
    scan_instruction: "सत्यता तपासण्यासाठी QR कोड फ्रेममध्ये ठेवा.",
    genuine: "अस्सल बियाणे",
    fake: "बनावट / नोंदणी नसलेले",
    fraud: "आधीच वापरलेले",
    manufacturer: "उत्पादक",
    batch: "बॅच क्रमांक",
    expiry: "कालबाह्यता तारीख",
    type: "बियाण्याचा प्रकार",
    ask_ai: "एग्री-बॉटला विचारा",
    ai_placeholder: "हे कसे लावायचे?",
    register_title: "उत्पादक नोंदणी",
    register_btn: "पॅकेट नोंदणी करा",
    fraud_map: "फसवणूक हीटमॅप",
    total_seeds: "एकूण बियाणे",
    total_scans: "एकूण स्कॅन",
    fraud_detected: "फसवणूक आढळली",
    back: "मागे",
    track: "पुरवठा साखळी",
    track_title: "पुरवठा साखळी अपडेट करा",
    track_btn: "ठिकाण अपडेट करा",
    journey: "बियाण्याचा प्रवास",
    rewards: "एग्री-टोकन",
    fraud_regions: "प्रादेशिक फसवणूक अहवाल",
    login: "लॉगिन",
    username: "वापरकर्ता नाव",
    password: "पासवर्ड",
    login_btn: "एग्रीट्रस्टमध्ये प्रवेश करा",
    logout: "लॉगआउट",
    welcome: "पुन्हा स्वागत आहे",
    farmer: "शेतकरी",
    manufacturer_role: "उत्पादक",
    admin_role: "प्रशासक",
    distributor_role: "वितरक",
    retailer_role: "किरकोळ विक्रेता",
    inspector_role: "गुणवत्ता निरीक्षक",
    logistics_role: "लॉजिस्टिक पार्टनर",
    profile: "प्रोफाइल",
    profile_info: "प्रोफाइल माहिती",
    stats: "आकडेवारी",
    member_since: "सदस्यता तारीख",
    total_verifications: "एकूण पडताळणी",
    total_registrations: "एकूण नोंदणी",
    account_status: "खाते स्थिती",
    verified_account: "पडताळलेले",
    signup: "साइन अप करा",
    signin: "साइन इन करा",
    create_account: "खाते तयार करा",
    have_account: "तुमचे आधीच खाते आहे का?",
    no_account: "तुमचे खाते नाही का?",
    role_select: "तुमची भूमिका निवडा",
    error_wrong_password: "चुकीचा पासवर्ड! कृपया पुन्हा प्रयत्न करा.",
    error_user_not_found: "वापरकर्ता सापडला नाही. कृपया साइन अप करा.",
    error_user_exists: "वापरकर्ता नाव आधीच अस्तित्वात आहे.",
    signup_title: "तुमचे खाते तयार करा",
    signup_subtitle: "तुमची बियाणे सुरक्षित करण्यासाठी एग्रीट्रस्टमध्ये सामील व्हा",
    signup_success: "खाते यशस्वीरित्या तयार झाले! कृपया साइन इन करा.",
    confirm_password: "पासवर्डची पुष्टी करा",
    error_password_mismatch: "पासवर्ड जुळत नाहीत!",
    full_name: "पूर्ण नाव",
    phone: "फोन नंबर",
    pref_lang: "पसंतीची भाषा",
    state: "राज्य",
    district: "जिल्हा",
    primary_crop: "मुख्य पीक",
    farm_area: "शेती क्षेत्र (एकर)",
    company_name: "कंपनीचे नाव",
    license_no: "परवाना क्रमांक",
    org_name: "संस्थेचे नाव",
    access_level: "प्रवेश स्तर",
    edit_profile: "प्रोफाइल संपादित करा",
    save_profile: "प्रोफाइल जतन करा",
    profile_updated: "प्रोफाइल यशस्वीरित्या अपडेट झाले!",
    last_login: "शेवटचे लॉगिन",
    marathi: "मराठी",
    english: "इंग्रजी",
    hindi: "हिंदी",
    intended_region: "नियोजित क्षेत्र",
    lab_report: "लॅब रिपोर्ट",
    report_fake: "बनावट बियाण्याची तक्रार करा",
    report_success: "तक्रार यशस्वीरित्या सबमिट झाली!",
    points_earned: "मिळवलेले गुण",
    expired: "कालबाह्य",
    recalled: "परत मागवलेले",
    near_expiry: "कालबाह्य होण्याच्या जवळ",
    recall_batch: "बॅच परत मागवा",
    download_qr: "QR डाउनलोड करा",
    print_label: "लेबल प्रिंट करा",
    compliance_score: "अनुपालन स्कोअर",
    fraud_heatmap: "फसवणूक हीटमॅप",
    live_alerts: "लाइव अलर्ट",
    blockchain_audit: "ब्लॉकचेन ऑडिट",
  },
};

export type Language = keyof typeof translations;
